name: Generate Videos

on:
  schedule:
    - cron: '0 6,14,22 * * *'  # Exécution à 6h, 14h et 22h UTC
  workflow_dispatch:  # Permet aussi le déclenchement manuel

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick ffmpeg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install moviepy==1.0.3
        pip install openai==1.12.0
        pip install deepl==1.17.0
        pip install Pillow==10.2.0
        pip install pytrends==4.9.2
        pip install gTTS==2.5.1
        pip install requests==2.31.0
        pip install python-dotenv==1.0.1
        pip install google-auth-oauthlib==1.2.0
        pip install google-auth-httplib2==0.2.0
        pip install google-api-python-client==2.120.0
        pip install instabot==0.117.0
        pip install tiktok-uploader==1.0.16

    - name: Generate and Upload Videos
      env:
        # OpenAI pour la génération de scripts
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
        # DeepL pour les traductions
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        
        # YouTube
        YOUTUBE_CLIENT_SECRETS: ${{ secrets.YOUTUBE_CLIENT_SECRETS }}
        
        # Instagram
        INSTAGRAM_USERNAME: "technosphereflux"
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        
        # Pexels pour les images
        PEXELS_API_KEY: "0Nd2ZIJSJHGRp1x4cBwauCPuCIH08CexznNpsuAw1sIbTaLH4wHRMN3d"
        
        # TikTok
        TIKTOK_SESSION: ${{ secrets.TIKTOK_SESSION }}
      run: |
        echo "$YOUTUBE_CLIENT_SECRETS" > youtube_credentials.json
        echo "$TIKTOK_SESSION" > tiktok_session.json
        python auto_generator.py

    - name: Upload Videos
      uses: actions/upload-artifact@v4
      with:
        name: generated-videos
        path: videos/ 